"""NWS station bias correction for model forecasts.

AUTO-GENERATED by scripts/build_bias_table.py on 2026-03-26.
Data period: 2026-02-24 to 2026-03-25 (30 days).

Bias corrections are computed as: -(mean(model_forecast - actual_observation))
Positive offset = model under-predicts (actual runs hotter than model)
Negative offset = model over-predicts (actual runs cooler than model)

These corrections are applied BEFORE consensus computation to improve
the accuracy of model-derived probabilities vs NWS resolution data.

Source: Open-Meteo Archive API (observations) + Historical Forecast API (model hindcasts).
Re-run the script periodically to keep corrections fresh.
"""
from __future__ import annotations

from dataclasses import dataclass

from weather_edge.models.enums import City, WeatherModel


@dataclass(frozen=True)
class BiasCorrection:
    """Temperature bias correction in degC for a model at a station."""

    temp_max_offset: float = 0.0  # Add this to model forecast (positive = model under-predicts)
    temp_min_offset: float = 0.0
    notes: str = ""


# Known biases: model_name -> city_id -> BiasCorrection
# Positive offset means model typically under-predicts (actual runs hotter)
# Negative offset means model typically over-predicts (actual runs cooler)
STATION_BIAS: dict[str, dict[City, BiasCorrection]] = {
    WeatherModel.ECMWF.value: {
        City.ATL: BiasCorrection(temp_max_offset=0.25, temp_min_offset=0.4, notes="30-day mean bias correction"),
        City.DAL: BiasCorrection(temp_max_offset=0.09, temp_min_offset=-0.24, notes="30-day mean bias correction"),
        City.LON: BiasCorrection(temp_max_offset=0.07, temp_min_offset=-0.15, notes="30-day mean bias correction"),
        City.NYC: BiasCorrection(temp_max_offset=0.8, temp_min_offset=-0.34, notes="30-day mean bias correction"),
        City.SEA: BiasCorrection(temp_max_offset=0.29, temp_min_offset=-0.1, notes="30-day mean bias correction"),
        City.SEL: BiasCorrection(temp_max_offset=1.68, temp_min_offset=-1.25, notes="30-day mean bias correction"),
        City.TOR: BiasCorrection(temp_max_offset=0.5, temp_min_offset=-0.02, notes="30-day mean bias correction"),
    },
    WeatherModel.GEM.value: {
        City.ATL: BiasCorrection(temp_max_offset=-0.16, temp_min_offset=1.14, notes="30-day mean bias correction"),
        City.DAL: BiasCorrection(temp_max_offset=-0.13, temp_min_offset=0.58, notes="30-day mean bias correction"),
        City.LON: BiasCorrection(temp_max_offset=-0.14, temp_min_offset=0.43, notes="30-day mean bias correction"),
        City.NYC: BiasCorrection(temp_max_offset=-0.14, temp_min_offset=-0.12, notes="30-day mean bias correction"),
        City.SEA: BiasCorrection(temp_max_offset=-0.35, temp_min_offset=0.49, notes="30-day mean bias correction"),
        City.SEL: BiasCorrection(temp_max_offset=1.27, temp_min_offset=1.12, notes="30-day mean bias correction"),
        City.TOR: BiasCorrection(temp_max_offset=-0.95, temp_min_offset=0.52, notes="30-day mean bias correction"),
    },
    WeatherModel.GFS.value: {
        City.ATL: BiasCorrection(temp_max_offset=-1.02, temp_min_offset=-0.31, notes="30-day mean bias correction"),
        City.DAL: BiasCorrection(temp_max_offset=-0.75, temp_min_offset=-0.28, notes="30-day mean bias correction"),
        City.LON: BiasCorrection(temp_max_offset=-0.28, temp_min_offset=-1.02, notes="30-day mean bias correction"),
        City.NYC: BiasCorrection(temp_max_offset=-1.0, temp_min_offset=-1.17, notes="30-day mean bias correction"),
        City.SEA: BiasCorrection(temp_max_offset=0.36, temp_min_offset=0.09, notes="30-day mean bias correction"),
        City.SEL: BiasCorrection(temp_max_offset=4.65, temp_min_offset=-3.62, notes="30-day mean bias correction"),
        City.TOR: BiasCorrection(temp_max_offset=-0.51, temp_min_offset=-0.84, notes="30-day mean bias correction"),
    },
    WeatherModel.ICON.value: {
        City.ATL: BiasCorrection(temp_max_offset=-0.04, temp_min_offset=-0.49, notes="30-day mean bias correction"),
        City.DAL: BiasCorrection(temp_max_offset=-0.86, temp_min_offset=-0.6, notes="30-day mean bias correction"),
        City.LON: BiasCorrection(temp_max_offset=-0.26, temp_min_offset=-1.01, notes="30-day mean bias correction"),
        City.NYC: BiasCorrection(temp_max_offset=-0.69, temp_min_offset=-2.06, notes="30-day mean bias correction"),
        City.SEA: BiasCorrection(temp_max_offset=0.03, temp_min_offset=-0.56, notes="30-day mean bias correction"),
        City.SEL: BiasCorrection(temp_max_offset=2.95, temp_min_offset=-3.58, notes="30-day mean bias correction"),
        City.TOR: BiasCorrection(temp_max_offset=0.42, temp_min_offset=-0.22, notes="30-day mean bias correction"),
    },
    WeatherModel.HRRR.value: {
        City.ATL: BiasCorrection(temp_max_offset=-1.02, temp_min_offset=-0.31, notes="30-day mean bias correction"),
        City.DAL: BiasCorrection(temp_max_offset=-0.75, temp_min_offset=-0.28, notes="30-day mean bias correction"),
        City.NYC: BiasCorrection(temp_max_offset=-1.0, temp_min_offset=-1.17, notes="30-day mean bias correction"),
        City.SEA: BiasCorrection(temp_max_offset=0.36, temp_min_offset=0.09, notes="30-day mean bias correction"),
    },
    WeatherModel.UKV.value: {
        City.LON: BiasCorrection(temp_max_offset=-0.41, temp_min_offset=-1.04, notes="30-day mean bias correction"),
    },
}

# Generic city-level bias (applied to ALL models for a city)
# These capture station-level biases independent of any particular model
# Computed as the average correction across all models analyzed for that city
CITY_BIAS: dict[City, BiasCorrection] = {
    City.ATL: BiasCorrection(
        temp_max_offset=-0.4,
        temp_min_offset=0.09,
        notes="Avg across 5 models, 30-day window",
    ),
    City.DAL: BiasCorrection(
        temp_max_offset=-0.48,
        temp_min_offset=-0.16,
        notes="Avg across 5 models, 30-day window",
    ),
    City.LON: BiasCorrection(
        temp_max_offset=-0.2,
        temp_min_offset=-0.56,
        notes="Avg across 5 models, 30-day window",
    ),
    City.NYC: BiasCorrection(
        temp_max_offset=-0.41,
        temp_min_offset=-0.97,
        notes="Avg across 5 models, 30-day window",
    ),
    City.SEA: BiasCorrection(
        temp_max_offset=0.14,
        temp_min_offset=0.0,
        notes="Avg across 5 models, 30-day window",
    ),
    City.SEL: BiasCorrection(
        temp_max_offset=2.64,
        temp_min_offset=-1.83,
        notes="Avg across 4 models, 30-day window",
    ),
    City.TOR: BiasCorrection(
        temp_max_offset=-0.14,
        temp_min_offset=-0.14,
        notes="Avg across 4 models, 30-day window",
    ),
}


def get_bias_correction(model_name: str, city_id: City) -> BiasCorrection:
    """Get the total bias correction for a model at a city.

    Combines model-specific and city-level biases.
    """
    model_bias = STATION_BIAS.get(model_name, {}).get(city_id, BiasCorrection())
    city_bias = CITY_BIAS.get(city_id, BiasCorrection())

    return BiasCorrection(
        temp_max_offset=model_bias.temp_max_offset + city_bias.temp_max_offset,
        temp_min_offset=model_bias.temp_min_offset + city_bias.temp_min_offset,
    )


def apply_bias_correction(
    value: float,
    variable: str,
    model_name: str,
    city_id: City,
) -> float:
    """Apply bias correction to a model forecast value.

    Returns the corrected value that should better match NWS observations.
    """
    correction = get_bias_correction(model_name, city_id)

    if "max" in variable:
        return value + correction.temp_max_offset
    elif "min" in variable:
        return value + correction.temp_min_offset

    return value
